### ISSUE TITLE
User_Role model

### ISSUE THREAD

**Issue by agustif** [smpallen99/contact_demo#16]
# TODO: In a later version of Ecto, can we remove this? imo, it doesn't need to be exposed as a first-class model

I saw this todo in the code, can this be improved now? Would it make a good PR?

We're on Ecto 2 so maybe the comment was with ecto 1.x

**Comment by vraravam** [comment]
from what I remember (I saw/tried out this codebase approx 2 years ago), this is due to the absence of the has-many-through (in Ecto 1.x). I was told that another contributor was working on fixing this, but I haven't seen any activity on merging fixes in the past 2 years.
