### ISSUE TITLE
CSS and JS assets not loading

### ISSUE THREAD

**Issue by vraravam** [smpallen99/contact_demo#2]
hi, I'm trying to use the exact downloaded version of the contact_demo app (downloaded as a zip). After running `mix deps.get` and `npm install` - I'm not able to get the CSS/Js files when running in development mode. Any help?

**Comment by smpallen99** [comment]
The installer adds instructions to your brunch-config.js file. Did you follow the instructions  and modify as directed?

**Comment by vraravam** [comment]
This is what I ended up with (that worked): https://gist.github.com/vraravam/e3da4300e58edc53ad8bc64d19f8c955

I still am not able to get the `Logout` and `Theme changer` menus to work - no drop-down.

Also, noticed that the `Add new Phone` in the contacts edit screen does not work anymore. Might all these be related?

**Comment by smpallen99** [comment]
Theme changer can get setup in config. You need to setup logout in the auth protocol.

**Comment by vraravam** [comment]
Sorry @smpallen99 : As mentioned, I have the **exact** code from your codebase - and these above issues are still present. I have not cloned or forked or anything - its a direct zip from your git repo page. 
Please help. Can I reopen?

**Comment by vraravam** [comment]
When I start up the server, this is the stack trace (warnings) that I get:

``` bash
[BABEL] Note: The code generator has deoptimised the styling of "deps/ex_admin/priv/static/js/admin_lte2.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "deps/ex_admin/priv/static/js/ex_admin_common.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "deps/ex_admin/priv/static/js/jquery.min.js" as it exceeds the max of "100KB".
09 Nov 07:30:57 - info: compiling.
09 Nov 07:30:57 - error: Processing of deps/ex_admin/priv/static/js/admin_lte2.js failed. Could not load module 'moment' from '/Users/vijay/Downloads/contact_demo/deps/ex_admin/priv/static/js'. Possible solution: add 'moment' to package.json and `npm install`.
09 Nov 07:30:57 - error: Processing of deps/ex_admin/priv/static/js/ex_admin_common.js failed. Could not load module 'jquery.mousewheel' from '/Users/vijay/Downloads/contact_demo/deps/ex_admin/priv/static/js'. Possible solution: add 'jquery.mousewheel' to package.json and `npm install`.
09 Nov 07:30:58 - info: compiled 8 files into 7 files, copied 3 in 11.3 sec
```

**Comment by smpallen99** [comment]
I downloaded the repo and set it up with two version of ex_admin. The locked version and the version after `mix deps.update ex_admin' without any issues.  So, I'm thinking it might be an npm version issue? I'm running npm 3.5.3.

After cloning the repo, compiling, setup the database, and running npm install, you need to run `mix admin.install` to move the assets into priv/static'. This worked for me.

If you update ex_admin and run `mix admin.install`, you need to update `brunch-config.js` file per the instructions appended to this file. I did this and everything worked fine.

what is the version of ex_admin in your `mix.lock` file?

Steve

**Comment by vraravam** [comment]
@smpallen99 : Thanks for reopening this. I was finally able to get this running. But, I'm not sure what steps I did to get here.

A couple of requests:
1. If you are dependent on any globally-installed packages for npm, please remove that dependency and push that also as part of `package.json`
2. Could you use `npm shrinlwrap` to lock down the npm packages to specific packages and commit that into the codebase? It might help others who land on this repo as a reference in the future to not have issues arising due to newer package versions.
3. If you are ok with it, I will try to upgrade each mix package to a newer version, and will test if things continue to work. Once I get these upgrades done, I would like to raise a PR to get this merged into your main repo. Is that ok with you?

**Comment by vraravam** [comment]
btw - I'm on npm version 3.10.8

**Comment by vraravam** [comment]
Closing this issue since its working now.
