### ISSUE TITLE
Inconsistent with v0.3.0 of coherence package

### ISSUE THREAD

**Issue by vraravam** [smpallen99/contact_demo#4]
I'm not sure whether to log the bug in the coherence repo or in this one. But, the problem is that with this code, I am unable to upgrade that package. Reason for upgrade: would like to have the 'register for account' functionality that was introduced after `v0.2.0`

**Comment by vraravam** [comment]
@smpallen99 - any help with this please ?

**Comment by smpallen99** [comment]
Since you did not provide any details in your issue, should I presume you want me to do this upgrade?

**Comment by vraravam** [comment]
Sorry, yes, I have the same repo as is in your master/HEAD. When I run `mix hex.outdated`, it shows this dependency alone as outdated. Upgrading it and running the `mix coherence.install` does some steps - after which the error occurs when starting up the application.
