### ISSUE TITLE
None of the filters work

### ISSUE THREAD

**Issue by vraravam** [smpallen99/contact_demo#8]
I tried with the latest code in contact_demo, and for eg in the contacts screen, I tried to search for "last_name" containing some characters. When the page refreshes, the selection (also reflected in the url as query parameters) always goes to the "Equals" selection for the first filtered field. I'm not sure if this is an issue with ex_admin or this codebase.

**Comment by smpallen99** [comment]
its either an issue with ex_admin or ex_queb. Please open an issue on ex_admin. 

Thansks, Steve

**Comment by smpallen99** [comment]
This is working on my local copy as well as other ex_admin projects I have. Please try `mix deps.update ex_queb` and retest.

**Comment by smpallen99** [comment]
Ok, your right. Its not working on the contacts page. Actually, the begins with filter is not working at all on contact. However, filters are working on other pages.

**Comment by smpallen99** [comment]
Found the issue in ex_admin so I'm closing this issue.
